version: '3.8'

services:

  phpfpm: 
    container_name: php
    image: 'bitnami/php-fpm:latest'
    volumes:
      - ./laravel-app:/var/www/html
    working_dir: /var/www/html
    networks:
      - internal

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./laravel-app:/var/www/html:rw
    ports:
      - "8080:80"
    networks:
      - internal

  db:
    container_name: db
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: laravel
      MYSQL_USER: thuc
      MYSQL_PASSWORD: 123456
    networks:
      - internal

  node:
    container_name: frontend
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./react-app:/var/www/html
    working_dir: /var/www/html
    networks:
      - internal
    environment:
      WATCHPACK_POLLING: true
    command:
      /bin/sh -c "npm install && npm start"

networks:
  internal:
    driver: bridge